name: Build with Maven

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"
      - run: mvn -B package
      - uses: actions/upload-artifact@v3
        with:
          name: target
          path: ./target/
