name: Coverity Scan

on:
  workflow_call:
    secrets:
      COVERITY_SCAN_EMAIL:
        required: true
      COVERITY_SCAN_TOKEN:
        required: true

jobs:
  Coverity:
    name: Coverity Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"
      - name: Coverity Scan
        uses: vapier/coverity-scan-action@v1
        with:
          build_language: "java"
          command: "mvn compile"
          email: ${{ secrets.COVERITY_SCAN_EMAIL }}
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverity-scan
          path: ./cov-int/
