name: Build with Quality Check
on:
  push:
    branches:
      - "*"

jobs:
  build:
    uses: ./.github/workflows/build-mvn-package.yml
  deploy:
    needs: build
    uses: ./.github/workflows/deploy-github.yml
  site:
    needs: build
    uses: ./.github/workflows/ghpages-mvn-site.yml
