name: Build with Quality Check
on:
  push:
    branches:
      - "*"

jobs:
  build:
    uses: ./.github/workflows/build-mvn-verify.yml
  coveralls:
    needs: build
    uses: ./.github/workflows/quality-coveralls.yml
    secrets:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  sonarcloud:
    needs: build
    uses: ./.github/workflows/quality-sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  codecov:
    needs: build
    uses: ./.github/workflows/quality-codecov.yml
  codacy:
    needs: build
    uses: ./.github/workflows/quality-codacy.yml
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
  codeclimate:
    needs: test
    uses: ./.github/workflows/quality-codeclimate.yml
    secrets:
      CODE_CLIMATE_REPORT_TOKEN: ${{ secrets.CODE_CLIMATE_REPORT_TOKEN }}
